## Graph construction using networkx and graph-tool

In [1]:
import networkx as nx
import numpy as np
from itertools import product
import numpy.ma as ma
from toolz.curried import pipe, curry
from toolz.curried import map as fmap
import zipfile
import pandas as pd
import time

from graph_tool.all import *
from graph_tool.topology import mark_subgraph
from graph_tool.centrality import betweenness

Import data files 

In [2]:
zip_stream = zipfile.ZipFile('../data/cahn-hilliard.zip', 'r')

def read_data(file_name):
    return np.array(
        pd.read_csv(
            zip_stream.open(file_name, 'r'),
            delimiter=' ',
            header=None               
        ).swapaxes(0, 1)
    )

data = np.array(
    list(
        map(read_data, zip_stream.namelist()[1:6])
    )
)

In [3]:
cond = lambda x: (x[:, 1] != -1) & (x[:, 0] != -1)


def merge_edges(neighbors, ids):
    return pipe(
        ids,
        lambda x: np.reshape(x.flatten(), (-1, 1, 1)),
        lambda x: np.repeat(x, neighbors.shape[1], axis=1),
        lambda x: np.concatenate((x, neighbors), axis=-1).reshape(-1, 2),
        lambda x: x[cond(x)],
    )


def index_vectors(nx, ny, nz):
    index2D = ([1, 0, 0], [1, 1, 0], [0, 1, 0], [-1, 1, 0])
    if ny == nz == 1:
        return ([1, 0, 0],)
    if nz == 1:
        return index2D
    else:
        return index2D + tuple([x, y, 1] for x in (1, 0, -1) for y in (1, 0, -1))


def make_ids_padded(ids):
    nx, ny, nz = ids.shape
    ids_padded = -np.ones((nx + 2, ny + 2, nz + 2), dtype=int)
    ids_padded[1:-1, 1:-1, 1:-1] = ids
    return ids_padded


@curry
def make_sub_ids(ids_padded, indices):
    nx, ny, nz = ids_padded.shape
    left, up, front = indices
    return ids_padded[
        1 + left : nx - 1 + left, 1 + up : ny - 1 + up, 1 + front : nz - 1 + front
    ][..., None]


def make_neighbors(ids):
    nx, ny, nz = ids.shape
    ids_padded = make_ids_padded(ids)

    return pipe(
        index_vectors(nx, ny, nz),
        fmap(make_sub_ids(ids_padded)),
        list,
        lambda x: np.concatenate(x, axis=-1).reshape(nx * ny * nz, len(x), 1),
    )


def make_grid_edges(nx=1, ny=1, nz=1):
    ids = np.arange(nx * ny * nz).reshape(nx, ny, nz)
    return merge_edges(make_neighbors(ids), ids)


def make_grid_graph(shape):
    g = nx.Graph()
    g.add_nodes_from(np.arange(np.prod(shape)))
    g.add_edges_from(make_grid_edges(*shape))
    return g

def make_grid_graph_gt(shape):
    g = Graph(directed = False)
    g.add_vertex(np.prod(shape))
    g.add_edge_list(make_grid_edges(*shape))
    return g

In [4]:
data = np.array([[0,0,0], [1,1,1], [0,0,0]])

In [5]:
def makeImageGraph_gt(morph):

    G = make_grid_graph_gt(morph.shape)
    interfacev = G.add_vertex()

    vertex_colors = morph.flatten()

    phase = G.new_vertex_property("int")
    for i in range(len(vertex_colors)):
        phase[i] = vertex_colors[i]
        
    phase[int(interfacev)] = -1
    G.vertex_properties["color"] = phase

    ## Add interface vertex and change edge connections for interface vertices
    G.set_fast_edge_removal(fast=True)
    efilt = G.new_edge_property('int');
    interface = []

    for e in G.edges():
        if phase[e.source()] != phase[e.target()]:
            efilt[e] = 1
            interface.append([int(e.source()), int(e.target())])
        else :
            efilt[e] = 0

    graph_tool.stats.remove_labeled_edges(G, efilt)

    interface = np.unique(np.array(interface)).flatten()
    interface_edges = np.vstack((interface, (np.array([int(interfacev)] * interface.shape[0])))).T

    G.add_edge_list(interface_edges)

    return G
def count_of_vertices_gt(G, phase):
    phases = np.array(list(G.vertex_properties["color"]))
    return (phases == phase).sum()

def makeConnectedComponents_gt(G, phase):
    interfacev = find_vertex(G, G.vertex_properties["color"], -1)
    phases = np.array(list(G.vertex_properties["color"]))
    if phase == 0:
        phases = 1 - phases
    vfilt = phases
    vfilt[int(interfacev[0])] = 0
    sub = GraphView(G, vfilt)
    return len(set(label_components(sub)[0]))

def interfaceArea_gt(G):
    interfacev = find_vertex(G, G.vertex_properties["color"], -1)[0]
    phases = np.array(list(G.vertex_properties["color"]))
    interface_1, interface_0 = 0, 0
    for w in G.iter_out_neighbors(interfacev):
        if phases[w] == 1:
            interface_1 += 1
        else: 
            interface_0 += 1
    return interface_1 + interface_0, interface_0, interface_1

def shortest_distance_gt(G):
    interfacev = find_vertex(G, G.vertex_properties["color"], -1)[0]
    phases = np.array(list(G.vertex_properties["color"]))

    d = shortest_distance(G, interfacev)
    dist_to_interface = sum(list(d))/max(1, (len(list(d)) - 1))

    vfilt = phases
    sub_1 = GraphView(G, vfilt)

    d = shortest_distance(sub_1, interfacev)
    dist_to_interface_1 = sum(list(d))/max(1, (len(list(d)) - 1))

    phases = 1 - phases
    vfilt_0 = phases
    sub_0 = GraphView(G, vfilt_0)

    d = shortest_distance(sub_0, interfacev)
    dist_to_interface_0 = sum(list(d))/max(1, (len(list(d)) - 1))

    return dist_to_interface, dist_to_interface_1, dist_to_interface_0


def surface_area(G, data_shape, phase):
    rows, cols = data_shape
    boundary_left = np.array([i for i in range(0,rows*cols,cols)])
    boundary_right = np.array([i for i in range(cols-1,rows*cols,cols)])
    boundary_top = np.array([i for i in range(0, cols)])
    boundary_bottom = np.array([i for i in range(rows*cols - cols, rows*cols)])
    
    phases = np.array(list(G.vertex_properties["color"])[:-1])
    if phase == 0: phases = 1 - phases
        
    return sum(phases[boundary_left]), sum(phases[boundary_right]), sum(phases[boundary_top]), sum(phases[boundary_bottom])
 
def surface_cc(G, data_shape):
    rows, cols = data.shape
    boundary_top = ([i for i in range(0, data.shape[1])])
    top = g.add_vertex()
    boundary_bottom = [i for i in range(rows*cols - cols, rows*cols)]
    bottom = g.add_vertex()
    boundary_left = [i for i in range(0,rows*cols,cols)]
    left = g.add_vertex()
    boundary_right = [i for i in range(cols-1,rows*cols,cols)]
    right = g.add_vertex()
    
    phases = (g.vertex_properties["color"])
    phases[top] = -2
    phases[bottom] = -2
    phases[left] = -2
    phases[right] = -2
    
    g.vertex_properties["color"] = phases
    
    boundary_edges = np.concatenate((np.array((list([int(top)] * len(boundary_top)), boundary_top)).T, 
                                     np.array((list([int(bottom)] * len(boundary_bottom)), boundary_bottom)).T,
                                     np.array((list([int(left)] * len(boundary_left)), boundary_left)).T,
                                     np.array((list([int(right)] * len(boundary_right)), boundary_right)).T), axis = 0)
    
    G.add_edge_list(boundary_edges)
    
    
    
    return G    
    

def getGraspiDescriptors_gt(data):
    g = makeImageGraph_gt(data)
    [interface_area, phase_0_interface, phase_1_interface] = interfaceArea_gt(g)
    [distance_to_interface, distance_to_interface_0, distance_to_interface_1] = shortest_distance_gt(g)
    [left_0, right_0, top_0, bottom_0]  = surface_area(g, data.shape, 0)
    [left_1, right_1, top_1, bottom_1]  = surface_area(g, data.shape, 1)
    return dict(
        phase_0_count=count_of_vertices_gt(g, 0),
        phase_1_count=count_of_vertices_gt(g, 1),
        phase_0_cc=makeConnectedComponents_gt(g, 0),
        phase_1_cc=makeConnectedComponents_gt(g, 1),
        interfacial_area=interface_area,
        phase_0_interface=phase_0_interface,
        phase_1_interface=phase_1_interface,
        distance_to_interface=distance_to_interface,
        distance_to_interface_0=distance_to_interface_0,
        distance_to_interface_1=distance_to_interface_1,
        left_boundary_count_0 = left_0,
        left_boundary_count_1 = left_1,
        right_boundary_count_0 = right_0,
        right_boundary_count_1 = right_1,
        top_boundary_count_0 = top_0,
        top_boundary_count_1 = top_1,
        bottom_boundary_count_0 = bottom_0,
        bottom_boundary_count_1 = bottom_1
    )


In [6]:
getGraspiDescriptors_gt(data)

{'phase_0_count': 6,
 'phase_1_count': 3,
 'phase_0_cc': 2,
 'phase_1_cc': 1,
 'interfacial_area': 9,
 'phase_0_interface': 6,
 'phase_1_interface': 3,
 'distance_to_interface': 1.0,
 'distance_to_interface_0': 1.0,
 'distance_to_interface_1': 1.0,
 'left_boundary_count_0': 2,
 'left_boundary_count_1': 1,
 'right_boundary_count_0': 2,
 'right_boundary_count_1': 1,
 'top_boundary_count_0': 3,
 'top_boundary_count_1': 0,
 'bottom_boundary_count_0': 3,
 'bottom_boundary_count_1': 0}

In [7]:
g = makeImageGraph_gt(data)


In [8]:
# Add boundary meta-vertices and make connections
rows, cols = data.shape
boundary_top = ([i for i in range(0, data.shape[1])])
top = g.add_vertex()
boundary_bottom = [i for i in range(rows*cols - cols, rows*cols)]
bottom = g.add_vertex()
boundary_left = [i for i in range(0,rows*cols,cols)]
left = g.add_vertex()
boundary_right = [i for i in range(cols-1,rows*cols,cols)]
right = g.add_vertex()


In [14]:
np.array([int(top)] * len(boundary_top))
a = np.array((list([int(top)] * len(boundary_top)), boundary_top)).T

In [15]:
b = np.array((list([int(bottom)] * len(boundary_bottom)), boundary_bottom)).T

In [11]:
np.array((list([int(left)] * len(boundary_left)), boundary_left)).T

array([[12,  0],
       [12,  3],
       [12,  6]])

In [12]:
np.array((list([int(right)] * len(boundary_right)), boundary_right)).T

array([[13,  2],
       [13,  5],
       [13,  8]])

In [9]:
boundary_edges = np.concatenate((np.array((list([int(top)] * len(boundary_top)), boundary_top)).T, 
                                     np.array((list([int(bottom)] * len(boundary_bottom)), boundary_bottom)).T,
                                     np.array((list([int(left)] * len(boundary_left)), boundary_left)).T,
                                     np.array((list([int(right)] * len(boundary_right)), boundary_right)).T), axis = 0)
    
g.add_edge_list(boundary_edges)

In [8]:
G = surface_cc(g, data.shape)

In [9]:
phases = np.array(list(G.vertex_properties["color"]))
phases

array([ 0,  0,  0,  1,  1,  1,  0,  0,  0, -1, -2, -2, -2, -2])

In [10]:
vfilt = phases
sub = GraphView(G, vfilt)


In [13]:
list(sub.vertices())

[<Vertex object with index '3' at 0x1687d73c0>,
 <Vertex object with index '4' at 0x1687d7140>,
 <Vertex object with index '5' at 0x1687d72c0>,
 <Vertex object with index '9' at 0x1687d75c0>,
 <Vertex object with index '10' at 0x1687fc040>,
 <Vertex object with index '11' at 0x1687fc0c0>,
 <Vertex object with index '12' at 0x1687fc140>,
 <Vertex object with index '13' at 0x1687fc1c0>]

ValueError: value must be of type PropertyMap, not <class 'numpy.ndarray'>

NameError: name 'interfacev' is not defined

In [26]:
sub = GraphView(g, top)

TypeError: 'Vertex' object is not callable

In [ ]:
## Transport properties

graph_tool.topology.all_circuits(g, unique=False)

In [6]:
def makeImageGraph(morph):
    
    G = make_grid_graph(morph.shape)
    vertex_colors = morph.flatten()
    mapping = {(i): vertex_colors[i] for i in range(len(vertex_colors))}
    nx.set_node_attributes(G, mapping, name="color")
    return G
 

def count_of_vertices(G, phase):
    
    phases = nx.get_node_attributes(G, "color")
    phase_list = list(phases.values())
    return phase_list.count(phase)


def node_phaseA(n, G):
    nodes = G.nodes
    return nodes[n]["color"] == 0


def node_phaseB(n, G):
    nodes = G.nodes
    return nodes[n]["color"] == 1


def makeInterfaceEdges(G):
    
    interface = [
        (n, u)
        for n, u in G.edges()
        if (node_phaseA(n, G) and node_phaseB(u, G))
        or (node_phaseB(n, G) and node_phaseA(u, G))
    ]
    G.remove_edges_from(interface)
    G.add_node(-1, color="green")
    interface = np.unique(np.array(interface))
    interface_edges = [(x, -1) for x in interface]
    G.add_edges_from(interface_edges)
    return G


def makeConnectedComponents(G, phase):
    
    nodes = (node for node, data in G.nodes(data=True) if data.get("color") == phase)
    subgraph = G.subgraph(nodes)
    subgraph.nodes
    return nx.number_connected_components(subgraph)


def interfaceArea(G):
    
    nodes_0 = [
        neighbor for neighbor in G.neighbors(-1) if G.nodes[neighbor]["color"] == 0
    ]
    nodes_1 = [
        neighbor for neighbor in G.neighbors(-1) if G.nodes[neighbor]["color"] == 1
    ]
    return G.degree[-1], len(nodes_0), len(nodes_1)


def shortest_distances_all(G):
    
    path = nx.single_source_shortest_path(G, -1)
    del path[-1]
    path_length = [len(p) for p in path.values()]
    # print(path_length)
    return sum(path_length) / len(path_length)


def shortest_distances_phase(G, phase):
    
    source = [node for node, data in G.nodes(data=True) if data.get("color") == phase]
    path = [
        nx.shortest_path(G, s, target=-1, weight=None, method="dijkstra")
        for s in source
    ]
    path_length = [len(p) for p in path]
    return sum(path_length) / len(path_length)
    
def getGraspiDescriptors(data):


    g = makeImageGraph(data)
    g = makeInterfaceEdges(g)
    [interface_area, phase_0_interface, phase_1_interface] = interfaceArea(g)

    return dict(
        phase_0_count=count_of_vertices(g, 0),
        phase_1_count=count_of_vertices(g, 1),
        phase_0_cc=makeConnectedComponents(g, 0),
        phase_1_cc=makeConnectedComponents(g, 1),
        interfacial_area=interface_area,
        phase_0_interface=phase_0_interface,
        phase_1_interface=phase_1_interface,
        distance_to_interface=shortest_distances_all(g),
        distance_to_interface_0=shortest_distances_phase(g, 0),
        distance_to_interface_1=shortest_distances_phase(g, 1),
    )

In [7]:
data.shape

(3, 3)

In [12]:
start_time = time.time()
pipe(
    data,
    fmap(getGraspiDescriptors_gt),
    list,
    lambda x: pd.DataFrame(x, columns=sorted(x[0].keys())),
)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.012317895889282227 seconds ---


In [9]:
start_time = time.time()
pipe(
    data,
    fmap(getGraspiDescriptors),
    list,
    lambda x: pd.DataFrame(x, columns=sorted(x[0].keys())),
)
print("--- %s seconds ---" % (time.time() - start_time))

--- 208.15930485725403 seconds ---


In [7]:
phase = G.new_vertex_property("int")
for i in range(len(vertex_colors)):
    phase[i] = vertex_colors[i]
phase[int(interfacev)] = -1
G.vertex_properties["color"] = phase


In [8]:
## Add interface vertex and change edge connections for interface vertices
phases = G.vertex_properties["color"]
efilt = G.new_edge_property('int');
interface = []
for e in G.edges():
    if phase[e.source()] != phase[e.target()]:
        efilt[e] = 1
        interface.append([int(e.source()), int(e.target())])
    else :
        efilt[e] = 0
graph_tool.stats.remove_labeled_edges(G, efilt)

In [9]:
interface = np.unique(np.array(interface)).flatten()
interface_edges = np.vstack((interface, (np.array([int(interfacev)] * interface.shape[0])))).T

G.add_edge_list(interface_edges)

In [10]:
# Count number of vertices
phase = 0
phases = np.array(list(G.vertex_properties["color"]))
(phases == phase).sum()

6

In [11]:
# Count of connected components for 2 phases
phases = np.array(list(G.vertex_properties["color"]))
#phases = 1 - phases  # count cc for second phase for an input with 2 phases
vfilt = phases
vfilt[int(interfacev)] = 0
sub = GraphView(G, vfilt)

cc = len(set(label_components(sub)[0]))
cc

1

In [12]:
phases

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [14]:
# Interfacial area
def interfaceArea(G):
    interfacev = find_vertex(G, G.vertex_properties["color"], -1)
    phases = np.array(list(G.vertex_properties["color"]))
    for w in g.iter_out_neighbors(interfacev):
        if phases[w] == 1:
            interface_1 += 1
        else: 
            interface_0 += 1
    return interface_1 + interface_0, iterface_0, interface_1
        

In [15]:
# Shortest distances

d = shortest_distance(G, interfacev)
dist_to_interface = sum(list(d))/(len(list(d)) - 1)
dist_to_interface

1.0

In [16]:
# Shortest distance to interface from a phase

phases = np.array(list(G.vertex_properties["color"]))
vfilt = phases
sub_1 = GraphView(G, vfilt)

d = shortest_distance(sub_1, interfacev)
dist_to_interface_1 = sum(list(d))/(len(list(d)) - 1)

phases = 1 - phases
vfilt_0 = phases
#vfilt_0[int(interfacev)] = 0
sub_0 = GraphView(G, vfilt_0)

d = shortest_distance(sub_0, interfacev)
dist_to_interface_0 = sum(list(d))/(len(list(d)) - 1)

array([ 0,  0,  0,  1,  1,  1,  0,  0,  0, -1])

In [20]:
g = complete_graph(30)
sub = complete_graph(10)

<Graph object, undirected, with 10 vertices and 45 edges, at 0x1622c6280>