## Identify intersections 


In [1]:
import networkx as nx
import numpy as np
from math import *

In [2]:
def getNeighborhood1D(dim_x, dim_y):
    vertex_list = np.array(range(dim_x * dim_y))
    #neighborhood = np.zeros([vertex_list.shape[0], 8])
    
    #del_vertices = []
    del_vertices = list(range(0,dim_x * dim_y,dim_x))
    del_vertices += (list(range(dim_x - 1,dim_x * dim_y,dim_x)))
    
    del_vertices += list(range(1,dim_x))
    del_vertices += list(range(dim_x * (dim_y - 1) + 1 ,dim_x * dim_y ))
    del_vertices = list(set(del_vertices))
   
    
    vertex_list =[i for i in range(dim_x * dim_y) if i not in del_vertices]
    neighborhood = np.array([[p-dim_x, (p-dim_x) + 1, p + 1, p + dim_x + 1, p + dim_x,
                             (p+dim_x) - 1, p - 1, (p - dim_x) - 1 ] for p in vertex_list ])
    return neighborhood, vertex_list

In [25]:
neighbors, vertex_list = getNeighborhood1D(7, 7)

vertex_list

[8,
 9,
 10,
 11,
 12,
 15,
 16,
 17,
 18,
 19,
 22,
 23,
 24,
 25,
 26,
 29,
 30,
 31,
 32,
 33,
 36,
 37,
 38,
 39,
 40]

In [26]:
neighbors

array([[ 1,  2,  9, 16, 15, 14,  7,  0],
       [ 2,  3, 10, 17, 16, 15,  8,  1],
       [ 3,  4, 11, 18, 17, 16,  9,  2],
       [ 4,  5, 12, 19, 18, 17, 10,  3],
       [ 5,  6, 13, 20, 19, 18, 11,  4],
       [ 8,  9, 16, 23, 22, 21, 14,  7],
       [ 9, 10, 17, 24, 23, 22, 15,  8],
       [10, 11, 18, 25, 24, 23, 16,  9],
       [11, 12, 19, 26, 25, 24, 17, 10],
       [12, 13, 20, 27, 26, 25, 18, 11],
       [15, 16, 23, 30, 29, 28, 21, 14],
       [16, 17, 24, 31, 30, 29, 22, 15],
       [17, 18, 25, 32, 31, 30, 23, 16],
       [18, 19, 26, 33, 32, 31, 24, 17],
       [19, 20, 27, 34, 33, 32, 25, 18],
       [22, 23, 30, 37, 36, 35, 28, 21],
       [23, 24, 31, 38, 37, 36, 29, 22],
       [24, 25, 32, 39, 38, 37, 30, 23],
       [25, 26, 33, 40, 39, 38, 31, 24],
       [26, 27, 34, 41, 40, 39, 32, 25],
       [29, 30, 37, 44, 43, 42, 35, 28],
       [30, 31, 38, 45, 44, 43, 36, 29],
       [31, 32, 39, 46, 45, 44, 37, 30],
       [32, 33, 40, 47, 46, 45, 38, 31],
       [33, 34, 

In [27]:
morph = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
morph = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])
morph.shape

(49,)

In [48]:
morph_neighbors = morph[neighbors]
morph_neighbors[morph[vertex_list] == 0, :] = 0
potential_junctions = np.argwhere(np.sum(morph_neighbors, axis=1) >= 3)
potential_junctions = np.squeeze(potential_junctions)
morph_neighbors

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0]])

In [29]:
# Neighbors of Potential Junctions
potential_junct_n = []
for i in potential_junctions:
    #print(list(np.where([morph_neighbors[i, :] == 1])[1]))
    #potential_junct_n.append(list(np.where(neighbors[morph_neighbors[i, :] == 1])[1]))
    k = neighbors[i][list(np.where([morph_neighbors[i, :] == 1])[1])]
    N = [i for i in range(len(vertex_list)) if vertex_list[i] in k]
    potential_junct_n.append(N)
potential_junct_n

[[2, 11, 12, 13],
 [7, 10, 12, 17],
 [7, 11, 13, 17],
 [7, 12, 14, 17, 19],
 [11, 12, 13, 23],
 [13, 14, 23, 24],
 [17, 19, 24]]

In [30]:
# Potential Junction Neighbors of Potential Junctions
potential_junct_junct_n = []
for i in potential_junct_n:
    l = []
    [l.append(p) for p in i if p in potential_junctions]
    potential_junct_junct_n.append(l)
potential_junct_junct_n
junc_even_n = morph_neighbors[:,0] + morph_neighbors[:,2] + morph_neighbors[:,4] + morph_neighbors[:,6]   
potential_junct_junct_n

[[11, 12, 13],
 [7, 12, 17],
 [7, 11, 13, 17],
 [7, 12, 17, 19],
 [11, 12, 13, 23],
 [13, 23],
 [17, 19]]

In [31]:
del_junctions = []
for i in range(len(potential_junctions)):
    this_junc = potential_junct_junct_n[i]
    for j in this_junc:
        pos, = np.where(potential_junctions == j)
        #print(pos[0])
        #if len(this_junc) > len(potential_junct_junct_n[pos[0]]):
        if junc_even_n[i] > junc_even_n[pos[0]]:
            if pos not in del_junctions : del_junctions.append(pos[0])
        #elif len(this_junc) < len(potential_junct_junct_n[pos[0]]):
        elif junc_even_n[i] < junc_even_n[pos[0]]:
            if i not in del_junctions : del_junctions.append(i)
potential_junctions[del_junctions]  

array([ 7, 11, 13, 17])

In [32]:
def elbow_check(l):
    if l[0] == 0 and l[-1] == 7: return True
    n = 2
    subs = [l[i:i+n] for i in range(len(l)) if len(l[i:i+n]) == n]
    return any([(sorted(sub) ==list(range(min(sub), max(sub)+1))) for sub in subs])

In [33]:
def connector_check(l):
    l.sort()
    if l[0] == 0 and l[-1] == 7: 
        subs = [[0, 1], l[1, 2]]
    else: 
        subs = [l[0, 1], l[2, 3]]
    return all([(sub ==list(range(min(sub), max(sub)+1))) for sub in subs])

In [46]:
def junc_elbows(morph_neighbors):
    pot_elbows = np.argwhere(np.sum(morph_neighbors, axis=1) == 3)
    for i in pot_elbows:
        #print(pot_elbows)
        l = np.where(morph_neighbors[i])[1]
        #print(l)
        if elbow_check(l) : print(i)
    pot_connnectors = np.argwhere(np.sum(morph_neighbors, axis=1) == 4)
    #print(pot_connnectors)
    for i in pot_connnectors[-1]:
        print(i)
        #print(pot_elbows)
        l = np.where(morph_neighbors[i])[1]
        #print(l)
        #if connector_check(l) : print(i)

In [47]:
junc_elbows(morph_neighbors)

[23]
19


IndexError: tuple index out of range